
version: '3'
services:
  # PostgresSQL service
  postgres:
    image: postgres-14-ep
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  # Airflow webserver service
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env
    environment:
      AIRFLOW_ADMIN_USERNAME: admin
      AIRFLOW_ADMIN_PASSWORD: Airflowtest
      AIRFLOW_ADMIN_FIRSTNAME: Admin
      AIRFLOW_ADMIN_LASTNAME: User
      AIRFLOW_ADMIN_EMAIL: admin@example.com
    ports:
      - "8080:8080"
    volumes:
      - ${HOST_LOGS_PATH}:/opt/airflow/logs
      - ${HOST_DAGS_PATH}:/opt/airflow/dags
    depends_on:
      - postgres
    networks:
      - airflow_network

  # Airflow scheduler service
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    env_file:
      - .env
    environment:
      AIRFLOW_ROLE: scheduler
    volumes:
      - ${HOST_LOGS_PATH}:/opt/airflow/logs
      - ${HOST_DAGS_PATH}:/opt/airflow/dags
    depends_on:
      - postgres
    networks:
      - airflow_network

  # Airflow worker service
  airflow-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    environment:
      AIRFLOW_ROLE: worker
    volumes:
      - ${HOST_LOGS_PATH}:/opt/airflow/logs
      - ${HOST_DAGS_PATH}:/opt/airflow/dags
    depends_on:
      - postgres
      - airflow-scheduler
    networks:
      - airflow_network

volumes:
  postgres_data:
    driver: local

networks:
  airflow_network:
    driver: bridge
